package com.chexun.dealer.model.dealers;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = false)
public class DealersInfo implements Serializable{
	private Long id;
    private String username;
    private String password;
    private String companyName;
    private String companyShortName;
    private Long companyType;
    private String salePhone;
    private String companyAddress;
    private Long provinceId;
    private Long cityId;
    private Long regionalId;
    private Long memberType;
    private String createTime;
    private Long state;
    private java.util.Date beginTime;
    private java.util.Date endTime;
    private String email;
    private String postalCode;
    private String servicePhone;
    private String maintainPhone;
    private String contact;
    private String companyWebsite;
    private String companyPhoto;
    private String starLever;
    private String makerAuthorizedProof;
    private String businessLicense;
    private String organization;
    private String contactCard;
    private String contactAuthorizedProof;
    private String serviceProjects;
    private String companyMap;
    private String companyIntroduction;
    private Long isCheck;
    private Long templateType;
    private String englishAlias;
    private String checkTime;
    private String checker;
    private String lastLoginTime;
    private String currentLoginTime;
    private Long operateBrandId;
    private String longitude;
    private String latitude;
    private Long dealerlevel;
    private Long updatecount;
    private java.util.Date updatetime;
    private Long isrecommendfirst;
    private String worktime;
    private String businfo;
    private String keyword;
    private Long districtid;
    private Long commercialid;
    private String remark;
    private Long datasource;
    private String bitauo400tel;
    private String companyWebsite2;
    private Long regionalid;
    private String fenji;
    private Long transfertime;
    private Long transfercycle;
    private String transferphone;
    private java.util.Date transferstartdate;
    private java.util.Date transferenddate;
    private String companyWebsite3;
    private Long pushcount;
    private Long allpushcount;
    private Long shop;
    private Long shopcount;
    private Long allshopcount;
    private String tel400;
    private String telid;
    private Long buycount;
    private java.util.Date buydate;
    private java.util.Date buyStartdate;
    private java.util.Date buyEnddate;
    private Long isjifen;
    private Long daorustatus;
    private java.math.BigDecimal baozhengjin;
    private java.math.BigDecimal frozenbaozhengjin;
    private Long frozenshopcount;
    private Long pushdealercount;
}
